apiVersion: v1
kind: Service
metadata:
  name: shopizer-backend
  namespace: shopizer-local
spec:
  selector:
    app: shopizer-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
